services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - user-service
      - inventory-service
      - requisition-service
      - reporting-service
    env_file:
      - ./api-gateway/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
