version: '3.8'

services:
  # User Service
  user-service:
    build:
      context: ./user-service
    ports:
      - "8001:8000"
    env_file:
      - ./user-service/.env
    networks:
      - backend-network
    depends_on:
      - user-db

  # User Database
  user-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: user_service_user
      MYSQL_PASSWORD: user_service_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - user-mysql-data:/var/lib/mysql
    networks:
      - backend-network

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8002:8000"
    env_file:
      - ./inventory-service/.env
    networks:
      - backend-network
    depends_on:
      - inventory-db

  # Inventory Database
  inventory-db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_service_user
      MYSQL_PASSWORD: inventory_service_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    networks:
      - backend-network

  # Requisition Service
  requisition-service:
    build:
      context: ./requisition-service
    ports:
      - "8005:8000"
    env_file:
      - ./requisition-service/.env
    networks:
      - backend-network
    depends_on:
      - requisition-db

  # Requisition Database
  requisition-db:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: requisition_db
      MYSQL_USER: requisition_service_user
      MYSQL_PASSWORD: requisition_service_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - requisition-mysql-data:/var/lib/mysql
    networks:
      - backend-network

  # Reporting Service
  reporting-service:
    build:
      context: ./reporting-service
    ports:
      - "8004:8000"
    env_file:
      - ./reporting-service/.env
    networks:
      - backend-network
    depends_on:
      - reporting-db

  # Reporting Database
  reporting-db:
    image: mysql:5.7
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: reporting_db
      MYSQL_USER: reporting_service_user
      MYSQL_PASSWORD: reporting_service_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - reporting-mysql-data:/var/lib/mysql
    networks:
      - backend-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8081:8080"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - user-service
      - inventory-service
      - requisition-service
      - reporting-service
    env_file:
      - ./api-gateway/.env

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - api-gateway
    networks:
      - frontend-network

  # Redis Service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend-network

volumes:
  user-mysql-data:
  inventory-mysql-data:
  requisition-mysql-data:
  reporting-mysql-data:
  celery-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
