version: '3.8'

services:
  # User Service
  user-service:
    build:
      context: ./user-service
    ports:
      - "8001:8000"
    env_file:
      - ./user-service/.env
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "until mysqladmin ping -h db -u user_db -psecurepassword --silent; do
        echo 'Waiting for database...'; 
        sleep 2; 
      done &&
      gunicorn --bind 0.0.0.0:8000 --workers 4 user_service.wsgi:application"
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user_db
      MYSQL_PASSWORD: securepassword
    volumes:
      - user-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8002:8000"
    environment:
      DB_HOST: inventory-db
      DB_PORT: "3306"
      DB_NAME: inventory_db
      DB_USER: inventory_user
      DB_PASSWORD: securepassword
    networks:
      - backend-network
    depends_on:
      inventory-db:
        condition: service_healthy
    command: >
      sh -c "while ! mysqladmin ping -h inventory-db -u inventory_user -psecurepassword --silent; do
        echo 'Waiting for database connection...';
        sleep 2;
      done &&
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 --workers 4 inventory_service.wsgi:application"
    restart: unless-stopped

  inventory-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: securepassword
    volumes:
      - inventory-mysql-data:/var/lib/mysql
      - ./inventory-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # Requisition Service
  requisition-service:
    build:
      context: ./requisition-service
    ports:
      - "8003:8000"
    env_file:
      - ./requisition-service/.env
    networks:
      - backend-network
    depends_on:
      - requisition-db
    restart: unless-stopped

  requisition-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    env_file:
      - ./requisition-service/db.env
    volumes:
      - requisition-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    restart: unless-stopped

  # Reporting Service
  reporting-service:
    build:
      context: ./reporting-service
    ports:
      - "8004:8000"
    env_file:
      - ./reporting-service/.env
    networks:
      - backend-network
    depends_on:
      - reporting-db
    restart: unless-stopped

  reporting-db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    env_file:
      - ./reporting-service/db.env
    volumes:
      - reporting-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8081:8080"
    env_file:
      - ./api-gateway/.env
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - user-service
      - inventory-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - frontend-network
    depends_on:
      - api-gateway
    restart: unless-stopped

volumes:
  user-mysql-data:
  inventory-mysql-data:
  redis-data:
  requisition-mysql-data:
  reporting-mysql-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
