services:
  # ========================
  # User Service
  # ========================
  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/db.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn user_service.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./user-service:/app
      - staticfiles:/app/staticfiles
    depends_on:
      - user-db
      - redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  db:
    image: mysql:8.0
    container_name: user-db
    env_file:
      - ./user-service/db.env
    volumes:
      - user-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Inventory Service
  # ========================
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    env_file:
      - ./inventory-service/db.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn inventory_service.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./inventory-service:/app
      - staticfiles:/app/staticfiles
    depends_on:
      - inventory-db
      - redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    env_file:
      - ./inventory-service/db.env
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Requisition Service
  # ========================
  requisition-service:
    build: ./requisition-service
    container_name: requisition-service
    env_file:
      - ./requisition-service/db.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn requisition_service.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./requisition-service:/app
      - staticfiles:/app/staticfiles
    depends_on:
      - requisition-db
      - redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  requisition-db:
    image: mysql:8.0
    container_name: requisition-db
    env_file:
      - ./requisition-service/db.env
    volumes:
      - requisition-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Reporting Service
  # ========================
  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    env_file:
      - ./reporting-service/db.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn reporting_service.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./reporting-service:/app
      - staticfiles:/app/staticfiles
    depends_on:
      - reporting-db
      - redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  reporting-db:
    image: mysql:8.0
    container_name: reporting-db
    env_file:
      - ./reporting-service/db.env
    volumes:
      - reporting-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Shared Dependencies
  # ========================
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # API Gateway
  # ========================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - inventory-service
      - requisition-service
      - reporting-service
    networks:
      - backend
    restart: always

  # ========================
  # Frontend
  # ========================
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - backend
    restart: always

# ========================
# Networks & Volumes
# ========================
networks:
  backend:
    driver: bridge

volumes:
  user-mysql-data:
  inventory-mysql-data:
  requisition-mysql-data:
  reporting-mysql-data:
  staticfiles:
