version: "3.9"

services:
  # ========================
  # User Service
  # ========================
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8000"
    env_file:
      - ./user-service/.env
    command: >
      sh -c "
        until nc -z user-db 3306;
        do echo 'Waiting for user-db...'; sleep 2; done;
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn user_service.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    restart: always

  user-db:
    image: mysql:8.0
    container_name: user-db
    env_file:
      - ./user-service/db.env
    ports:
      - "3311:3306"
    volumes:
      - user-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Inventory Service
  # ========================
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8009:8000"
    env_file:
      - ./inventory-service/.env
    command: >
      sh -c "
        until nc -z inventory-db 3306;
        do echo 'Waiting for inventory-db...'; sleep 2; done;
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn inventory_service.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      inventory-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    restart: always

  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    env_file:
      - ./inventory-service/db.env
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Requisition Service
  # ========================
  requisition-service:
    build: ./requisition-service
    container_name: requisition-service
    ports:
      - "8003:8000"
    env_file:
      - ./requisition-service/.env
    command: >
      sh -c "
        until nc -z requisition-db 3306;
        do echo 'Waiting for requisition-db...'; sleep 2; done;
        if [ '$$DJANGO_ENV' = 'production' ];
        then
          gunicorn requisition_service.wsgi:application --bind 0.0.0.0:8000 --workers 4;
        else
          python manage.py runserver 0.0.0.0:8000;
        fi"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      requisition-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    restart: always

  requisition-db:
    image: mysql:8.0
    container_name: requisition-db
    env_file:
      - ./requisition-service/db.env
    volumes:
      - requisition-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Reporting Service
  # ========================
  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    ports:
      - "8010:8000"
    env_file:
      - ./reporting-service/.env
    command: >
      sh -c "
        until nc -z reporting-db 3306;
        do echo 'Waiting for reporting-db...'; sleep 2; done;
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn reporting_service.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - staticfiles:/app/staticfiles
    depends_on:
      reporting-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    restart: always

  reporting-db:
    image: mysql:8.0
    container_name: reporting-db
    env_file:
      - ./reporting-service/db.env
    volumes:
      - reporting-mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================
  # Redis
  # ========================
  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - backend
    restart: always

  # ========================
  # API Gateway
  # ========================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:80"
    depends_on:
      user-service:
        condition: service_started
      inventory-service:
        condition: service_started
      requisition-service:
        condition: service_started
      reporting-service:
        condition: service_started
    networks:
      - backend
    restart: always

  # ========================
  # Frontend (PRODUCTION SETUP - RECOMMENDED)
  # ========================
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: sh -c "npm run dev -- --host 0.0.0.0 && tail -f /dev/null"
    ports:
      - "5173:5173"
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - backend
    restart: always

# ========================
# Networks & Volumes
# ========================
networks:
  backend:
    driver: bridge

volumes:
  user-mysql-data:
  inventory-mysql-data:
  requisition-mysql-data:
  reporting-mysql-data:
  staticfiles: