version: '3.8'

services:
  # User Service
  user-service:
    build:
      context: ./user-service
    ports:
      - "8001:8000"
    env_file:
      - ./user-service/.env
    networks:
      - backend-network
    depends_on:
      - db
    command: >
      sh -c "until nc -z db 3306; do
      echo 'Waiting for database...'; sleep 2; done &&
      gunicorn --bind 0.0.0.0:8000 --workers 4 user_service.wsgi:application"
    restart: unless-stopped

  # User Database
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user_db
      MYSQL_PASSWORD: securepassword
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZ: 1
    volumes:
      - user-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # User Celery
  user-celery:
    build:
      context: ./user-service
    command: celery -A user_service worker --loglevel=info --concurrency=4
    depends_on:
      - redis
      - db
    environment:
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 3306
      DJANGO_DB_NAME: user_db
      DJANGO_DB_USER: user_service_user
      DJANGO_DB_PASSWORD: user_service_password
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - backend-network
    restart: unless-stopped

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8002:8000"
    env_file:
      - ./inventory-service/.env
    networks:
      - backend-network
    depends_on:
      - inventory-db
    command: >
      sh -c "until nc -z inventory-db 3306; do
      echo 'Waiting for database...'; sleep 2; done &&
      gunicorn --bind 0.0.0.0:8000 --workers 4 inventory_service.wsgi:application"
    restart: unless-stopped

  # Inventory Database
  inventory-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_service_user
      MYSQL_PASSWORD: inventory_service_password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZ: 1
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # Requisition Service
  requisition-service:
    build:
      context: ./requisition-service
    ports:
      - "8003:8000"
    env_file:
      - ./requisition-service/.env
    networks:
      - backend-network
    depends_on:
      - requisition-db
    restart: unless-stopped

  requisition-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
      MYSQL_DATABASE: requisition_db
      MYSQL_USER: user_requisition_db
      MYSQL_PASSWORD: securepassword
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZ: 1
    volumes:
      - requisition-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    restart: unless-stopped

  # Reporting Service
  reporting-service:
    build:
      context: ./reporting-service
    ports:
      - "8004:8000"
    env_file:
      - ./reporting-service/.env
    networks:
      - backend-network
    depends_on:
      - reporting-db
    restart: unless-stopped

  reporting-db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
      MYSQL_DATABASE: reporting_db
      MYSQL_USER: reporting_service_user
      MYSQL_PASSWORD: reporting_service_password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZ: 1
    volumes:
      - reporting-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8081:8080"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - user-service
      - inventory-service
    env_file:
      - ./api-gateway/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - frontend-network
    depends_on:
      - api-gateway
    restart: unless-stopped

volumes:
  user-mysql-data:
  inventory-mysql-data:
  redis-data:
  requisition-mysql-data:
  reporting-mysql-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge