services:
  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - amms-network

  # Backend Service (Django)
version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8000"
    env_file:
      - ./user-service/.env
    networks:
      - amms

  inventory-service:
    build: ./inventory-service
    ports:
      - "8002:8000"
    env_file:
      - ./inventory-service/.env
    networks:
      - amms

  requisition-service:
    build: ./requisition-service
    ports:
      - "8003:8000"
    env_file:
      - ./requisition-service/.env
    networks:
      - amms

  reporting-service:
    build: ./reporting-service
    ports:
      - "8004:8000"
    env_file:
      - ./reporting-service/.env
    networks:
      - amms

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - amms
    depends_on:
      - user-service
      - inventory-service
      - requisition-service
      - reporting-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - amms
    depends_on:
      - api-gateway

networks:
  amms:
    driver: bridge

  # Redis Service (Optional for caching)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - amms-network

  # Celery Service (Optional for async tasks)
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: celery -A ammsbackend worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - amms-network

volumes:
  amms-mysql-data:

networks:
  amms-network:
    driver: bridge
