# The 'version' tag is obsolete and has been removed.
services:
  # User Service
  user-service:
    build:
      context: ./user-service
    ports:
      - "8001:8000"
    env_file:
      - ./user-service/.env
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy # Wait for the DB to be healthy
    command: >
      sh -c "until mysql --ssl-mode=DISABLED -h db -u$$DJANGO_DB_USER -p$$DJANGO_DB_PASSWORD -e 'SELECT 1;' ; do
      echo 'Waiting for user database...'; sleep 2; done &&
      gunicorn --bind 0.0.0.0:8000 --workers 4 user_service.wsgi:application"
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    # FIX: Use environment mapping instead of a separate db.env file
    environment:
      MYSQL_DATABASE: ${DJANGO_DB_NAME}
      MYSQL_USER: ${DJANGO_DB_USER}
      MYSQL_PASSWORD: ${DJANGO_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./user-service/.env # Load variables for substitution
    volumes:
      - user-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      # FIX: Use the correct variables for the healthcheck
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${DJANGO_DB_USER}", "-p$${DJANGO_DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # ... (user-celery service) ...

  # Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8009:8000"
    env_file:
      - ./inventory-service/.env
    networks:
      - backend-network
    depends_on:
      inventory-db:
        condition: service_healthy # Wait for the DB to be healthy
    command: >
      sh -c "until mysql --ssl-mode=DISABLED -h inventory-db -u$$DJANGO_DB_USER -p$$DJANGO_DB_PASSWORD -e 'SELECT 1;' ; do
      echo 'Waiting for inventory database...'; sleep 2; done &&
      gunicorn --bind 0.0.0.0:8000 --workers 4 inventory_service.wsgi:application"
    restart: unless-stopped

  inventory-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DJANGO_DB_NAME}
      MYSQL_USER: ${DJANGO_DB_USER}
      MYSQL_PASSWORD: ${DJANGO_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - ./inventory-service/.env
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${DJANGO_DB_USER}", "-p$${DJANGO_DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # Requisition Service
  requisition-service:
    build:
      context: ./requisition-service
    ports:
      - "8003:8000"
    env_file:
      - ./requisition-service/.env
    networks:
      - backend-network
    depends_on:
      requisition-db:
        condition: service_healthy # Wait for the DB to be healthy
    command: >
      sh -c "until mysql --ssl-mode=DISABLED -h requisition-db -u$$DJANGO_DB_USER -p$$DJANGO_DB_PASSWORD -e 'SELECT 1;' ; do
      echo 'Waiting for requisition database...'; sleep 2; done &&
      python manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 --workers 4 requisition_service.wsgi:application"
    restart: unless-stopped

  requisition-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: requisition_db
      MYSQL_USER: requisition_service
      MYSQL_PASSWORD: securepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    env_file:
      - ./requisition-service/.env
    volumes:
      - requisition-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$${DJANGO_DB_USER}", "-p$${DJANGO_DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # ... (other services like reporting, api-gateway, redis, frontend) ...

volumes:
  user-mysql-data:
  inventory-mysql-data:
  redis-data:
  requisition-mysql-data:
  reporting-mysql-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge