# Generated by Django 5.2.1 on 2025-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(default='', max_length=100)),
                ('rank', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('station_unit', models.CharField(default='', max_length=100)),
                ('firearm_type', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'requisition_service_requisition',
            },
        ),
    ]
