services:
  user-service:
    build: .
    container_name: user-service
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles

  user-db:
    image: mysql:8.0
    container_name: user-db
    restart: always
    env_file:
      - db.env
    ports:
      - "3311:3306"
    volumes:
      - user-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  celery-worker:
    build: .
    container_name: celery-worker
    env_file:
      - .env
    command: celery -A user_service worker --loglevel=info
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: celery-beat
    env_file:
      - .env
    command: celery -A user_service beat --loglevel=info
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

volumes:
  user-mysql-data:
  redis-data:
  staticfiles: