version: "3.9"

services:
  user-service:
    build: .
    container_name: user-service
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - db.env
    ports:
      - "3311:3306"
    volumes:
      - user-mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  celery-worker:
    build: .
    container_name: celery-worker
    env_file:
      - .env
    command: celery -A user_service worker --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: celery-beat
    env_file:
      - .env
    command: celery -A user_service beat --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  user-mysql-data:
  redis-data:
  staticfiles:
