# Generated by Django 5.2.5 on 2025-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serial Number')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('calibre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calibre')),
                ('type', models.CharField(choices=[('pistol', 'Pistol'), ('rifle', 'Rifle'), ('shotgun', 'Shotgun'), ('submachine_gun', 'Submachine Gun'), ('sniper_rifle', 'Sniper Rifle'), ('other', 'Other')], max_length=30, verbose_name='Type')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Firearm',
                'verbose_name_plural': 'Firearms',
                'ordering': ['serial_number'],
            },
        ),
    ]
