# Generated by Django 4.2.23 on 2025-08-08 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arm',
            options={'ordering': ['serial_number'], 'verbose_name': 'Firearm', 'verbose_name_plural': 'Firearms'},
        ),
        migrations.RemoveField(
            model_name='arm',
            name='category',
        ),
        migrations.RemoveField(
            model_name='arm',
            name='name',
        ),
        migrations.RemoveField(
            model_name='arm',
            name='status',
        ),
        migrations.AddField(
            model_name='arm',
            name='calibre',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Calibre'),
        ),
        migrations.AddField(
            model_name='arm',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='arm',
            name='model',
            field=models.CharField(default='Unknown Model', max_length=100, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='arm',
            name='type',
            field=models.CharField(choices=[('pistol', 'Pistol'), ('rifle', 'Rifle'), ('shotgun', 'Shotgun'), ('submachine_gun', 'Submachine Gun'), ('sniper_rifle', 'Sniper Rifle'), ('grenade_launcher', 'Grenade Launcher'), ('revolver', 'Revolver'), ('assault_rifle', 'Assault Rifle'), ('other', 'Other')], default='other', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='arm',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='arm',
            name='serial_number',
            field=models.CharField(default='UNKNOWN', max_length=100, unique=True, verbose_name='Serial Number'),
        ),
    ]
