# Generated by Django 4.2.23 on 2025-08-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_service', '0002_alter_arm_options_remove_arm_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arm',
            name='quantity',
        ),
    ]
