services:
  inventory-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    env_file:
      - db.env
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysql", "-uinventory_user", "-psecurepassword", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  inventory-service:
    build:
      context: .
    ports:
      - "8009:8000"
    env_file:
      - ./.env
    networks:
      - backend-network
    depends_on:
      inventory-db:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: inventory_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network
    restart: unless-stopped

  celery:
    build:
      context: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - inventory-db
    networks:
      - backend-network
    command: ["celery", "-A", "inventory_service", "worker", "--loglevel=info"]
    restart: unless-stopped

volumes:
  inventory-mysql-data:

networks:
  backend-network:
    driver: bridge