version: '3.8'

services:
  inventory-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=inventory-db
      - DJANGO_DB_PORT=3306
    depends_on:
      - inventory-db
    volumes:
      - .:/app

  celery:
    build: .
    environment:
      - DJANGO_DB_HOST=inventory-db
      - DJANGO_DB_PORT=3306
    depends_on:
      - inventory-db
      - redis
    volumes:
      - .:/app
    command: celery -A your_project_name worker --loglevel=info

  inventory-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: securepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"